Changed main character
paubenthem/MNXB01-learn pull request #1
Opened 2021-10-15 17:37 UTC by floridop

Changed: princess to mage
Added: ASCII art about mage

Is this ok?

2021-10-15 17:52 UTC, paubenthem commented
Hi Florido,

Please make the requested changes for the merge to be accepted

2021-10-15 21:04 UTC, floridop commented
Hi @paubenthem 
I suspect you made comments in the "Files changed" tab but did not press "start a review" so I actually cannot see any request! Sorry that part is not really explained in the slides. Maybe this can help:
https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews

2021-10-16 16:10 UTC, paubenthem requested changes
Hi Florido,

Please make the requested changes for the merge to be accepted

Thanks for the link! I hope this works now

2021-10-16 16:10 UTC, paubenthem commented on README.md
> +         jgs  / \`-'/ \
Please, remove "jgs" and "     " instead

2021-10-16 16:10 UTC, paubenthem commented on README.md
> +-=[ mage ]=-  10/98
Please remove these two lines

2021-10-16 16:56 UTC, floridop commented on README.md
> +         jgs  / \`-'/ \
I'd rather not do this, it's the initials of the author and I think it should not be removed.

2021-10-16 16:56 UTC, floridop commented on README.md
> +-=[ mage ]=-  10/98
sure!

2021-10-16 16:59 UTC, floridop commented on README.md
> +-=[ mage ]=-  10/98
change applied in commit 99ff078562e2ea00171fd12b3f1220421946375a

2021-10-17 06:26 UTC, paubenthem commented on README.md
> +         jgs  / \`-'/ \
Ok, I understand! It can stay then

2021-10-17 06:27 UTC, paubenthem commented
Thank you for the changes. I will merge the pull request

2021-10-17 06:27 UTC, merged